name: Auto Draft Failed PRs

on:
  workflow_run:
    workflows: ["Test CI"]
    types:
      - completed

jobs:
  auto-draft:
    name: Convert PR to Draft on CI Failure
    runs-on: ubuntu-latest

    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion != 'success'

    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Get PR Number
        id: get_pr_number
        run: |
          PR_URL=$(jq -r '.workflow_run.pull_requests[0].url' "$GITHUB_EVENT_PATH")
          if [ "$PR_URL" == "null" ]; then
            echo "No PR found. Exiting."
            exit 0
          fi
          PR_NUMBER=$(basename "$PR_URL")
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV

      - name: Convert PR to draft
        run: |
          echo "Converting PR #$PR_NUMBER to draft"
          gh pr ready --undo "$PR_NUMBER"
          gh pr comment "$PR_NUMBER" --body "🚧 PR automatically converted to draft because CI failed. Please fix and mark as ready again."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
