name: Auto Draft Failed PRs
on:
  workflow_run:
    workflows: ["Test CI"]  # Must match the name from the CI workflow
    types:
      - completed

jobs:
  auto-draft:
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.conclusion == 'failure'

    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Get PR Number
        id: pr
        run: |
          PR_URL=$(jq -r '.workflow_run.pull_requests[0].url' "$GITHUB_EVENT_PATH")
          if [ "$PR_URL" == "null" ]; then
            echo "No PR associated. Exiting."
            exit 0
          fi
          PR_NUMBER=$(echo "$PR_URL" | awk -F'/' '{print $NF}')
          echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT

      - name: Convert PR to draft
        if: steps.pr.outputs.pr_number != ''
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr_number = Number("${{ steps.pr.outputs.pr_number }}");
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr_number
            });

            if (pr.draft) {
              console.log(`PR #${pr_number} is already a draft.`);
              return;
            }

            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr_number,
              draft: true
            });

            console.log(`PR #${pr_number} converted to draft.`);

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr_number,
              body: `🚧 CI failed, PR automatically converted to draft.`
            });
