name: Auto Draft Failed PRs

on:
  workflow_run:
    workflows: ["Test CI"] # must exactly match your CI workflow name
    types:
      - completed

jobs:
  auto-draft:
    name: Convert PR to Draft on CI Failure
    runs-on: ubuntu-latest

    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion != 'success' &&
      github.event.workflow_run.conclusion != 'skipped'

    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Get PR Number
        id: get_pr_number
        run: |
          PR_URL=$(jq -r '.workflow_run.pull_requests[0].url' "$GITHUB_EVENT_PATH")
          if [ "$PR_URL" == "null" ]; then
            echo "No associated PR found. Exiting."
            exit 0
          fi
          PR_NUMBER=$(basename "$PR_URL")
          echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT

      - name: Convert PR to Draft & Comment
        if: steps.get_pr_number.outputs.pr_number != ''
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ steps.get_pr_number.outputs.pr_number }}
          REPO: ${{ github.repository }}
          CI_RUN_URL: ${{ github.event.workflow_run.html_url }}
          CONCLUSION: ${{ github.event.workflow_run.conclusion }}
        run: |
          echo "Converting PR #$PR_NUMBER to draft..."
          gh pr ready --undo "$PR_NUMBER" -R "$REPO"
          echo "PR converted."

          echo "Commenting..."
          gh pr comment "$PR_NUMBER" -R "$REPO" --body "🚧 PR automatically converted to draft because the **CI checks** failed (${CONCLUSION}). See details: ${CI_RUN_URL}"
          echo "Comment posted."
