name: Auto Draft Failed PRs

on:
  workflow_run:
    workflows: ["Test CI"]  # Replace with your actual workflow name
    types:
      - completed

jobs:
  auto-draft:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.conclusion != 'success' &&
      github.event.workflow_run.event == 'pull_request'

    permissions:
      pull-requests: write  # Required to modify PR state
      contents: read       # Required to read PR information

    steps:
      - name: Get PR Number
        id: get_pr
        run: |
          PR_URL=$(jq -r '.workflow_run.pull_requests[0].url' "$GITHUB_EVENT_PATH")
          if [ "$PR_URL" == "null" ]; then
            echo "No PR found"
            exit 0
          fi
          PR_NUMBER=$(basename "$PR_URL")
          echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT

      - name: Convert PR to Draft & Comment
        uses: actions/github-script@v7
        if: steps.get_pr.outputs.pr_number
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = Number('${{ steps.get_pr.outputs.pr_number }}');
            
            // Get PR details using the REST API
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber
            });

            // Check if the PR is already a draft
            if (pr.data.draft) {
              console.log(`PR #${prNumber} is already a draft`);
              return;
            }

            // Convert the PR to a draft using the REST API
            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              draft: true
            });

            console.log(`PR #${prNumber} converted to draft`);

            // Post a comment on the PR to notify the user
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: `🚧 PR automatically converted to draft because CI checks failed. See details: ${{ github.event.workflow_run.html_url }}`
            });

            console.log(`Commented on PR #${prNumber}`);
