# .github/workflows/test-ci.yml
name: Test CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check branch name
        id: check-branch
        run: |
          if [[ "${{ github.head_ref }}" == *"fail"* ]]; then
            echo "Should fail this test"
            exit 1
          else
            echo "Test passing"
          fi